version: '3.8'

services:
    parser:
        container_name: php_parser
        build: ../wb-importer/docker/php
        working_dir: /app
        volumes:
            - .:/app
        env_file:
            - .env
        command: tail -f /dev/null
